name: Stream Download to FTP

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Download URLs (space separated)"
        required: true
        type: string

      ftp_host:
        description: "FTP Host (example: 2193182633.cloudydl.com)"
        required: true
        type: string

      ftp_user:
        description: "FTP Username"
        required: true
        type: string

      ftp_pass:
        description: "FTP Password"
        required: true
        type: string

      ftp_path:
        description: "FTP Upload Path"
        required: false
        default: "/"
        type: string

jobs:
  transfer:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 curl lftp

      - name: Prepare folder
        run: mkdir -p files

      - name: Download files
        run: |
          URLS="${{ github.event.inputs.urls }}"

          for URL in $URLS; do
            echo "Downloading: $URL"

            aria2c \
              -x 16 \
              -s 16 \
              -k 1M \
              --file-allocation=none \
              --content-disposition=true \
              --dir=files \
              "$URL"

          done

      - name: Upload to FTP
        run: |
          HOST="${{ github.event.inputs.ftp_host }}"
          USER="${{ github.event.inputs.ftp_user }}"
          PASS="${{ github.event.inputs.ftp_pass }}"
          PATH="${{ github.event.inputs.ftp_path }}"

          lftp -u "$USER","$PASS" "ftp://$HOST" -e "
          set ftp:passive-mode true
          set net:max-retries 2
          set net:timeout 20
          mirror -R files $PATH --parallel=4
          quit
          "

      - name: Finished
        run: echo "Transfer completed"
